"""add_evidence_anchors_table

Revision ID: 104add14a387
Revises: b8d7a6c4e2f1
Create Date: 2026-03-14 00:57:21.650298

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '104add14a387'
down_revision: Union[str, Sequence[str], None] = 'b8d7a6c4e2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'evidence_anchors',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('call_session_id', sa.Uuid(), nullable=False),
        sa.Column(
            'artifact_type',
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column('artifact_id', sa.Uuid(), nullable=False),
        sa.Column(
            'field_name',
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column('transcript_utterance_id', sa.Uuid(), nullable=True),
        sa.Column('quote_text', sa.Text(), nullable=False),
        sa.Column('speaker', sa.String(length=64), nullable=False),
        sa.Column('sequence_number', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['call_session_id'],
            ['call_sessions.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['transcript_utterance_id'],
            ['transcript_utterances.id'],
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_evidence_anchors_artifact',
        'evidence_anchors',
        ['artifact_type', 'artifact_id'],
        unique=False,
    )
    op.create_index(
        'ix_evidence_anchors_call_session_id',
        'evidence_anchors',
        ['call_session_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_evidence_anchors_call_session_id',
        table_name='evidence_anchors',
    )
    op.drop_index(
        'ix_evidence_anchors_artifact',
        table_name='evidence_anchors',
    )
    op.drop_table('evidence_anchors')
    # ### end Alembic commands ###
