"""add_snapshot_tables

Revision ID: 2c30964a416a
Revises: 104add14a387
Create Date: 2026-03-14 01:19:21.163121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c30964a416a'
down_revision: Union[str, Sequence[str], None] = '104add14a387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deal_snapshots',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('deal_id', sa.Uuid(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column(
            'coverage_status',
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            'open_questions_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'key_signals_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['deal_id'], ['deals.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_deal_snapshots_deal_id',
        'deal_snapshots',
        ['deal_id'],
        unique=False,
    )
    op.create_table(
        'stakeholder_snapshots',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('role_label', sa.String(length=64), nullable=True),
        sa.Column('role_confidence', sa.Float(), nullable=True),
        sa.Column('stance', sa.String(length=64), nullable=True),
        sa.Column('sentiment', sa.String(length=64), nullable=True),
        sa.Column(
            'open_questions_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['stakeholder_id'],
            ['stakeholders.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_stakeholder_snapshots_stakeholder_id',
        'stakeholder_snapshots',
        ['stakeholder_id'],
        unique=False,
    )
    op.create_table(
        'risk_snapshots',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('deal_id', sa.Uuid(), nullable=False),
        sa.Column('call_session_id', sa.Uuid(), nullable=True),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('level', sa.String(length=32), nullable=False),
        sa.Column(
            'factors_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'change_summary_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'model_metadata_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['call_session_id'],
            ['call_sessions.id'],
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['deal_id'], ['deals.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_risk_snapshots_deal_id',
        'risk_snapshots',
        ['deal_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_risk_snapshots_deal_id',
        table_name='risk_snapshots',
    )
    op.drop_table('risk_snapshots')
    op.drop_index(
        'ix_stakeholder_snapshots_stakeholder_id',
        table_name='stakeholder_snapshots',
    )
    op.drop_table('stakeholder_snapshots')
    op.drop_index(
        'ix_deal_snapshots_deal_id',
        table_name='deal_snapshots',
    )
    op.drop_table('deal_snapshots')
    # ### end Alembic commands ###
