"""add_deals_stakeholders_call_sessions_call_events

Revision ID: 30770fd16af2
Revises: 1a9f7f7e5d8b
Create Date: 2026-03-13 13:41:19.116817

"""
# ruff: noqa: E501, I001
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30770fd16af2'
down_revision: Union[str, Sequence[str], None] = '1a9f7f7e5d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=64), server_default=sa.text("'discovery'"), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('risk_score_current', sa.Integer(), nullable=True),
    sa.Column('risk_level_current', sa.String(length=32), nullable=True),
    sa.Column('coverage_status_current', sa.String(length=64), nullable=True),
    sa.Column('summary_current', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deals_org_id', 'deals', ['org_id'], unique=False)
    op.create_index('ix_deals_owner_user_id', 'deals', ['owner_user_id'], unique=False)
    op.create_table('stakeholders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('role_label_current', sa.String(length=64), nullable=True),
    sa.Column('role_confidence_current', sa.Float(), nullable=True),
    sa.Column('stance_current', sa.String(length=64), nullable=True),
    sa.Column('sentiment_current', sa.String(length=64), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=32), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('manual', 'inferred')", name='ck_stakeholders_source_type'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stakeholders_deal_id', 'stakeholders', ['deal_id'], unique=False)
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_call_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'initiating'"), nullable=False),
    sa.Column('processing_status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('provider_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_status IN ('pending', 'transcript_partial', 'transcript_finalized', 'extraction_running', 'extraction_completed', 'snapshots_updating', 'risk_running', 'recommendation_completed', 'failed_retryable', 'failed_terminal')", name='ck_call_sessions_processing_status'),
    sa.CheckConstraint("status IN ('initiating', 'queued', 'ringing', 'in_progress', 'completed', 'no_answer', 'busy', 'failed', 'canceled')", name='ck_call_sessions_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_sessions_deal_id', 'call_sessions', ['deal_id'], unique=False)
    op.create_index('ix_call_sessions_stakeholder_id', 'call_sessions', ['stakeholder_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_events_call_session_id', 'call_events', ['call_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_events_call_session_id', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index('ix_call_sessions_stakeholder_id', table_name='call_sessions')
    op.drop_index('ix_call_sessions_deal_id', table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index('ix_stakeholders_deal_id', table_name='stakeholders')
    op.drop_table('stakeholders')
    op.drop_index('ix_deals_owner_user_id', table_name='deals')
    op.drop_index('ix_deals_org_id', table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
