"""add_transcript_utterances_table

Revision ID: a423fcbdf422
Revises: 676d1d63d2c4
Create Date: 2026-03-14 00:19:18.002466

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a423fcbdf422'
down_revision: Union[str, Sequence[str], None] = '676d1d63d2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transcript_utterances',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('call_session_id', sa.Uuid(), nullable=False),
        sa.Column(
            'provider_segment_id',
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column('speaker', sa.String(length=64), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('start_ms', sa.Integer(), nullable=True),
        sa.Column('end_ms', sa.Integer(), nullable=True),
        sa.Column('sequence_number', sa.Integer(), nullable=False),
        sa.Column(
            'is_final',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['call_session_id'],
            ['call_sessions.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_transcript_utterances_call_session_id',
        'transcript_utterances',
        ['call_session_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_transcript_utterances_call_session_id',
        table_name='transcript_utterances',
    )
    op.drop_table('transcript_utterances')
    # ### end Alembic commands ###
